//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageWallService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ImageWallServiceDataModelContainer : DbContext
    {
        public ImageWallServiceDataModelContainer()
            : base("name=ImageWallServiceDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ImageDetails> ImageDetailsSet { get; set; }
        public DbSet<ImageTag> ImageTagSet { get; set; }
        public DbSet<User> UserSet { get; set; }
    }
}
