//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageWallService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageDetails
    {
        public ImageDetails()
        {
            this.ImageTag = new HashSet<ImageTag>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Hash { get; set; }
        public System.DateTime Date { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public string URL { get; set; }
        public string URLThumb { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ImageTag> ImageTag { get; set; }
    }
}
