//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageWallService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageTag
    {
        public ImageTag()
        {
            this.ImageDetails = new HashSet<ImageDetails>();
        }
    
        public int Id { get; set; }
        public string Alias { get; set; }
        public int Size { get; set; }
        public bool IsPopular { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<ImageDetails> ImageDetails { get; set; }
    }
}
