//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageWallService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ImageTag = new HashSet<ImageTag>();
            this.ImageDetails = new HashSet<ImageDetails>();
        }
    
        public int Id { get; set; }
        public bool IsRegistered { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<ImageTag> ImageTag { get; set; }
        public virtual ICollection<ImageDetails> ImageDetails { get; set; }
    }
}
